// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByKyPZK_y7Rc3LrF8J4hp-sg9TdBJBdEU',
    appId: '1:756169448817:web:a880917ff7b9c03d292ad0',
    messagingSenderId: '756169448817',
    projectId: 'parkiing-3fad9',
    authDomain: 'parkiing-3fad9.firebaseapp.com',
    storageBucket: 'parkiing-3fad9.appspot.com',
    measurementId: 'G-BGHDCRB109',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoTEMpUkd-9WzpGQr1uaRhK1TPL4krflo',
    appId: '1:756169448817:android:c12ea78612110c81292ad0',
    messagingSenderId: '756169448817',
    projectId: 'parkiing-3fad9',
    storageBucket: 'parkiing-3fad9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_mA0wlNxkEYAtFRd3w5iviKAzxUMPIAs',
    appId: '1:756169448817:ios:0765aa21a69997d0292ad0',
    messagingSenderId: '756169448817',
    projectId: 'parkiing-3fad9',
    storageBucket: 'parkiing-3fad9.appspot.com',
    iosBundleId: 'com.example.parking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_mA0wlNxkEYAtFRd3w5iviKAzxUMPIAs',
    appId: '1:756169448817:ios:0765aa21a69997d0292ad0',
    messagingSenderId: '756169448817',
    projectId: 'parkiing-3fad9',
    storageBucket: 'parkiing-3fad9.appspot.com',
    iosBundleId: 'com.example.parking',
  );
}
