class PaymobAPIConstants {
  static const String apiKey =
      'ZXlKaGJHY2lPaUpJVXpVeE1pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmpiR0Z6Y3lJNklrMWxjbU5vWVc1MElpd2ljSEp2Wm1sc1pWOXdheUk2T1Rjek1EQXhMQ0p1WVcxbElqb2lhVzVwZEdsaGJDSjkuTFJkQVp2M21LX2dWYXlZTnN6ck1lZFBKSWo1Rk5oZjBWMWtSVFhJdVVTRFhEdkM3c3djNXltbmhvUlAzUnVYdXBBOTRXQW5jRXJ4MTAtRHJ0eFpTZ1E=';

  static const String integrationId = '';
}
